#!/bin/bash

echo "bootstrap instance for apache tomcat development"

sudo apt update
sudo apt install tree default-jdk ant git -y

java -version
ant -version
git --version

mkdir -p ~/dev/tomcat-build-libs
echo 'JAVA_HOME=/usr/lib/jvm/default-java/; export JAVA_HOME' >> ~/.bashrc

git clone https://github.com/apache/tomcat.git ~/dev/tomcat
echo 'TOMCAT_SRC=~/dev/tomcat; export TOMCAT_SRC' >> ~/.bashrc

cp ./build.properties ~/dev/tomcat/build.properties

sudo apt install software-properties-common apt-transport-https wget -y
wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" -y
sudo apt install code

